=== erikyo/wpmm/tests/fixtures/schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"properties": {
		"wordpress": {
			"type": "object",
			"properties": {
				"name": {
					"type": "string"
				},
				"version": {
					"type": "string"
				},
				"language": {
					"type": "string"
				},
				"WP_config": {
					"type": "object",
					"properties": {
						"DB_NAME": {
							"type": "string"
						},
						"DB_USER": {
							"type": "string"
						},
						"DB_PASSWORD": {
							"type": "string"
						},
						"DB_HOST": {
							"type": "string"
						},
						"DB_CHARSET": {
							"type": "string"
						},
						"DB_COLLATE": {
							"type": "string"
						},
						"table_prefix": {
							"type": "string"
						},
						"WP_DEBUG": {
							"type": "boolean"
						}
					},
					"required": [
						"DB_NAME",
						"DB_USER",
						"DB_PASSWORD",
						"DB_HOST",
						"DB_CHARSET",
						"table_prefix",
						"WP_DEBUG"
					]
				}
			},
			"required": ["name", "version", "language", "WP_config"]
		},
		"database": {
			"type": "object",
			"properties": {
				"type": {
					"type": "string"
				},
				"filename": {
					"type": "string"
				}
			},
			"required": ["type", "filename"]
		},
		"themes": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"name": {
						"type": "string"
					},
					"version": {
						"type": "string"
					},
					"source": {
						"type": "string"
					}
				},
				"required": ["name", "version"]
			}
		},
		"plugins": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"name": {
						"type": "string"
					},
					"version": {
						"type": "string"
					},
					"source": {
						"type": "string"
					}
				},
				"required": ["name", "version"]
			}
		},
		"postInstall": {
			"type": "array",
			"items": {
				"type": "string"
			}
		}
	},
	"required": ["wordpress", "database", "themes", "plugins", "postInstall"]
}

=== erikyo/wpmm/tests/fixtures/wp-package.json
{
	"$schema": "https://gist.githubusercontent.com/erikyo/7bcebc6d6e540eef3d1d92e37c0f9020/raw/77cfb0a932465c351f24a5a89c3641b0a8a08876/wpmm-schema.json",
	"wordpress": {
		"name": "wordpress",
		"version": "6.4.2",
		"language": "en_US",
		"WP_config": {
			"DB_NAME": "my_db_name",
			"DB_USER": "my_db_username",
			"DB_PASSWORD": "my_db_password",
			"DB_HOST": "localhost",
			"DB_CHARSET": "utf8",
			"DB_COLLATE": "",
			"table_prefix": "wp_",
			"WP_DEBUG": true
		}
	},
	"database": {
		"type": "mysql",
		"filename": "databases/database.sql"
	},
	"themes": [
		{
			"name": "modul-r",
			"version": "1.4.4",
			"source": "https://github.com/wp-blocks/modul-r.git"
		}
	],
	"plugins": [
		{
			"name": "contact-form-7",
			"version": "5.8.4"
		},
		{
			"name": "cf7-antispam",
			"version": "0.4.5",
			"source": "https://github.com/wp-blocks/cf7-antispam/archive/refs/heads/main.zip"
		}
	],
	"postInstall": [
		"wp cache flush",
		"wp plugin install $(wp plugin list --field=name) --force"
	]
}
